version: '3'
services:
  queue:
    image: rabbitmq:3.7.2
    ports:
      - "5672:5672"
    networks:
      - queue

  recommedation_service:
    build: ./recommedation_service
    command: python3 recommendation_app.py
    depends_on:
      - queue
    networks:
      - queue

  parser:
    build: ./parser
    command: python3 parser.py
    depends_on:
      - queue
    networks:
      - queue

  web_server:
    build: ./web_server
    command: python3 rest_api/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - queue
    networks:
      - queue

networks:
  queue:
    driver: bridge